// src/components/ComponentPreview.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import Button from './Button.vue'

const props = defineProps<{
  title: string
  description?: string
  code: string
  componentName?: string
}>()

const isCodeVisible = ref(false)
const responsiveMode = ref('desktop') // desktop, tablet, mobile

const toggleCode = () => {
  isCodeVisible.value = !isCodeVisible.value
}

const setResponsiveMode = (mode: string) => {
  responsiveMode.value = mode
}

const previewClasses = computed(() => {
  switch (responsiveMode.value) {
    case 'mobile':
      return 'w-full max-w-[375px] mx-auto'
    case 'tablet':
      return 'w-full max-w-[768px] mx-auto'
    default:
      return 'w-full'
  }
})

const formatCode = (code: string) => {
  return code.trim()
}
</script>

<template>
  <div class="component-preview mb-8 border border-border rounded-lg overflow-hidden">
    <!-- Header -->
    <div class="bg-card border-b border-border p-4 flex justify-between items-center">
      <div>
        <h3 class="text-lg font-heading font-semibold">{{ title }}</h3>
        <p v-if="description" class="text-sm text-muted-foreground mt-1">{{ description }}</p>
      </div>
      <div class="flex items-center gap-2">
        <!-- Responsive Controls -->
        <div class="flex border border-border rounded-md overflow-hidden">
          <button 
            @click="setResponsiveMode('desktop')" 
            class="p-2 text-sm transition-colors"
            :class="responsiveMode === 'desktop' ? 'bg-primary text-white' : 'bg-card hover:bg-muted'"
            aria-label="Desktop view"
          >
            <div class="i-mdi-monitor text-lg"></div>
          </button>
          <button 
            @click="setResponsiveMode('tablet')" 
            class="p-2 text-sm transition-colors"
            :class="responsiveMode === 'tablet' ? 'bg-primary text-white' : 'bg-card hover:bg-muted'"
            aria-label="Tablet view"
          >
            <div class="i-mdi-tablet text-lg"></div>
          </button>
          <button 
            @click="setResponsiveMode('mobile')" 
            class="p-2 text-sm transition-colors"
            :class="responsiveMode === 'mobile' ? 'bg-primary text-white' : 'bg-card hover:bg-muted'"
            aria-label="Mobile view"
          >
            <div class="i-mdi-cellphone text-lg"></div>
          </button>
        </div>
        
        <!-- Code Toggle -->
        <Button 
          variant="outline-primary" 
          size="sm" 
          @click="toggleCode"
          class="flex items-center gap-1"
        >
          <div class="i-mdi-code-tags text-lg"></div>
          <span>{{ isCodeVisible ? 'Hide Code' : 'View Code' }}</span>
        </Button>
      </div>
    </div>
    
    <!-- Preview Area -->
    <div class="bg-background p-6 border-b border-border">
      <div :class="previewClasses" class="transition-all duration-300">
        <slot></slot>
      </div>
    </div>
    
    <!-- Code Area -->
    <div v-if="isCodeVisible" class="bg-muted p-4 overflow-x-auto">
      <pre class="text-sm text-foreground"><code>{{ formatCode(code) }}</code></pre>
    </div>
  </div>
</template>

// src/components/ComponentPreview.tsx
import React, { ReactNode, useState } from 'react';
import { Code } from 'lucide-react';

interface ComponentPreviewProps {
  title: string;
  description?: string;
  children: ReactNode;
  code?: string;
}

const ComponentPreview: React.FC<ComponentPreviewProps> = ({
  title,
  description,
  children,
  code,
}) => {
  const [showCode, setShowCode] = useState(false);
  
  return (
    <div className="rounded-lg border border-border bg-card shadow-sm mb-10 overflow-hidden">
      <div className="px-6 py-4 border-b border-border">
        <div className="flex justify-between items-center">
          <h3 className="text-xl font-semibold">{title}</h3>
          {code && (
            <button 
              onClick={() => setShowCode(!showCode)}
              className="inline-flex items-center text-sm text-muted-foreground hover:text-foreground gap-1.5 px-2 py-1 rounded-md hover:bg-muted transition-colors"
            >
              <Code size={16} />
              <span>{showCode ? 'Hide code' : 'Show code'}</span>
            </button>
          )}
        </div>
        {description && <p className="text-muted-foreground mt-1">{description}</p>}
      </div>
      
      <div className="p-6 bg-component-preview-bg">
        <div className="flex flex-col gap-6 w-full">
          {children}
        </div>
      </div>
      
      {code && showCode && (
        <div className="p-4 bg-component-code-bg border-t border-border">
          <pre className="text-sm overflow-x-auto p-4 rounded-md bg-muted">
            <code>{code}</code>
          </pre>
        </div>
      )}
    </div>
  );
};

export default ComponentPreview;
