// src/components/layout/Navbar.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Icon } from '@iconify/vue'
import ThemeCustomizer from './ThemeCustomizer.vue'

defineProps<{
  isDark: boolean
}>()

const emit = defineEmits<{
  (e: 'toggleTheme'): void
}>()

const showCustomizer = ref(false)

const toggleCustomizer = () => {
  showCustomizer.value = !showCustomizer.value
}
</script>

<template>
  <header class="sticky top-0 z-40 border-b border-border bg-bg-primary shadow-sm">
    <div class="container mx-auto px-4 py-3 flex items-center justify-between">
      <div class="flex items-center gap-2">
        <div class="w-8 h-8 flex items-center justify-center bg-primary rounded-md text-text-inverted">
          <Icon icon="carbon:palette" class="text-2xl" />
        </div>
        <h1 class="text-xl font-bold">Design System</h1>
      </div>
      
      <div class="flex items-center gap-4">
        <button 
          class="p-2 rounded-full hover:bg-bg-muted transition-colors"
          @click="emit('toggleTheme')"
          title="Toggle theme"
        >
          <Icon :icon="isDark ? 'carbon:sun' : 'carbon:moon'" class="text-xl" />
        </button>
        
        <button 
          class="p-2 rounded-full hover:bg-bg-muted transition-colors"
          @click="toggleCustomizer"
          title="Customize theme"
        >
          <Icon icon="carbon:settings-adjust" class="text-xl" />
        </button>
      </div>
    </div>
    
    <ThemeCustomizer v-if="showCustomizer" @close="showCustomizer = false" />
  </header>
</template>

// src/components/Navbar.tsx
import React, { useState } from 'react';
import { Moon, Sun, Palette, Sliders } from 'lucide-react';
import { useTheme } from '../lib/hooks/useTheme';
import ThemeCustomizer from './ThemeCustomizer';

const Navbar: React.FC = () => {
  const { theme, setTheme } = useTheme();
  const [isThemeCustomizerOpen, setIsThemeCustomizerOpen] = useState(false);
  
  const toggleTheme = () => {
    setTheme(theme === 'light' ? 'dark' : 'light');
  };
  
  const toggleThemeCustomizer = () => {
    setIsThemeCustomizerOpen(!isThemeCustomizerOpen);
  };
  
  return (
    <header className="sticky top-0 z-40 w-full border-b border-border bg-background shadow-sm">
      <div className="container mx-auto flex h-16 items-center justify-between px-4">
        <div className="flex items-center gap-3">
          <div className="text-primary-600 dark:text-primary-400">
            <svg width="32" height="32" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M12 2L2 7L12 12L22 7L12 2Z" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
              <path d="M2 17L12 22L22 17" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
              <path d="M2 12L12 17L22 12" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
            </svg>
          </div>
          <div className="font-bold text-xl tracking-tight">Design System</div>
        </div>
        
        <div className="flex items-center gap-4">
          <button
            onClick={toggleTheme}
            className="inline-flex h-9 w-9 items-center justify-center rounded-md border border-input bg-background p-2 text-sm font-medium hover:bg-muted transition-colors"
            title={theme === 'light' ? 'Switch to dark theme' : 'Switch to light theme'}
          >
            {theme === 'light' ? <Moon size={18} /> : <Sun size={18} />}
            <span className="sr-only">Toggle theme</span>
          </button>
          
          <button
            onClick={toggleThemeCustomizer}
            className="inline-flex h-9 items-center justify-center rounded-md border border-input bg-background px-3 py-2 text-sm font-medium hover:bg-muted transition-colors gap-2"
            title="Customize theme"
          >
            <Sliders size={16} />
            <span>Customize</span>
          </button>
        </div>
      </div>
      
      {isThemeCustomizerOpen && (
        <ThemeCustomizer onClose={() => setIsThemeCustomizerOpen(false)} />
      )}
    </header>
  );
};

export default Navbar;
