// src/lib/components/Button.tsx
import React, { ButtonHTMLAttributes, forwardRef } from 'react';

export type ButtonVariant = 'primary' | 'secondary' | 'outline' | 'destructive' | 'ghost' | 'link';
export type ButtonSize = 'small' | 'default' | 'large';

export interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: ButtonVariant;
  size?: ButtonSize;
  leftIcon?: React.ReactNode;
  rightIcon?: React.ReactNode;
  isLoading?: boolean;
  isDisabled?: boolean;
  fullWidth?: boolean;
}

const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  (
    {
      children,
      variant = 'primary',
      size = 'default',
      leftIcon,
      rightIcon,
      isLoading = false,
      isDisabled = false,
      fullWidth = false,
      className = '',
      ...props
    },
    ref
  ) => {
    const baseClasses = 'inline-flex items-center justify-center font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 focus-visible:ring-offset-2 disabled:opacity-50 disabled:pointer-events-none';
    
    const variantClasses = {
      primary: 'bg-primary-600 text-white hover:bg-primary-700 active:bg-primary-800',
      secondary: 'bg-secondary-100 text-secondary-900 hover:bg-secondary-200 active:bg-secondary-300',
      outline: 'border border-input bg-transparent hover:bg-muted hover:text-foreground',
      destructive: 'bg-error-500 text-white hover:bg-error-600 active:bg-error-700',
      ghost: 'hover:bg-muted hover:text-foreground',
      link: 'text-primary-600 underline-offset-4 hover:underline',
    };
    
    const sizeClasses = {
      small: 'text-sm h-8 px-3 py-1 rounded-md',
      default: 'text-base h-10 px-4 py-2 rounded-md',
      large: 'text-lg h-12 px-6 py-3 rounded-lg',
    };
    
    const widthClass = fullWidth ? 'w-full' : '';
    
    const classes = [
      baseClasses,
      variantClasses[variant],
      sizeClasses[size],
      widthClass,
      className,
    ].join(' ');
    
    return (
      <button
        ref={ref}
        className={classes}
        disabled={isDisabled || isLoading}
        {...props}
      >
        {isLoading && (
          <span className="mr-2 inline-block animate-spin">
            <svg className="h-4 w-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
            </svg>
          </span>
        )}
        
        {!isLoading && leftIcon && <span className="mr-2">{leftIcon}</span>}
        {children}
        {!isLoading && rightIcon && <span className="ml-2">{rightIcon}</span>}
      </button>
    );
  }
);

Button.displayName = 'Button';

export { Button };

// src/components/ui/Button.vue
<script setup lang="ts">
import { computed } from 'vue'

const props = withDefaults(defineProps<{
  variant?: 'primary' | 'secondary' | 'outline' | 'destructive' | 'ghost' | 'link'
  size?: 'small' | 'default' | 'large'
  disabled?: boolean
  type?: 'button' | 'submit' | 'reset'
  icon?: boolean
}>(), {
  variant: 'primary',
  size: 'default',
  disabled: false,
  type: 'button',
  icon: false
})

const emit = defineEmits<{
  (e: 'click', event: MouseEvent): void
}>()

const buttonClasses = computed(() => {
  const classes = ['inline-flex items-center justify-center font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2']
  
  // Size classes
  if (props.size === 'small') {
    classes.push('text-sm h-8 px-3 rounded-md')
  } else if (props.size === 'large') {
    classes.push('text-base h-12 px-6 rounded-lg')
  } else {
    classes.push('text-sm h-10 px-4 rounded-md')
  }
  
  // Icon button
  if (props.icon) {
    if (props.size === 'small') {
      classes.push('h-8 w-8 p-0')
    } else if (props.size === 'large') {
      classes.push('h-12 w-12 p-0')
    } else {
      classes.push('h-10 w-10 p-0')
    }
  }
  
  // Variant classes
  if (props.variant === 'primary') {
    classes.push('bg-primary text-text-inverted hover:bg-primary-700 active:bg-primary-800')
  } else if (props.variant === 'secondary') {
    classes.push('bg-bg-muted text-text-primary hover:bg-bg-muted/80 active:bg-bg-muted/90')
  } else if (props.variant === 'outline') {
    classes.push('border border-border bg-transparent hover:bg-bg-muted active:bg-bg-muted/80')
  } else if (props.variant === 'destructive') {
    classes.push('bg-red-500 text-white hover:bg-red-600 active:bg-red-700')
  } else if (props.variant === 'ghost') {
    classes.push('bg-transparent hover:bg-bg-muted active:bg-bg-muted/80')
  } else if (props.variant === 'link') {
    classes.push('bg-transparent text-primary underline-offset-4 hover:underline')
  }
  
  // Disabled state
  if (props.disabled) {
    classes.push('opacity-50 cursor-not-allowed pointer-events-none')
  }
  
  return classes.join(' ')
})

const handleClick = (event: MouseEvent) => {
  if (!props.disabled) {
    emit('click', event)
  }
}
</script>

<template>
  <button
    :type="type"
    :class="buttonClasses"
    :disabled="disabled"
    @click="handleClick"
  >
    <slot />
  </button>
</template>
